server:
  port: 80
spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/person-bill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: guofu
    password: 310015
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 测试时关闭缓存，正式场合需要开启
  thymeleaf:
    cache: false
mybatis:
  # 实体类所在的包
  type-aliases-package: com.kkb.ggf.bill.pojo
  # 接口对应的xml所在的位置
  mapper-locations: classpath:mapper/**/*.xml
  # sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

